config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  
  resources :movies do
    resources :roles
  end
  
  resources :actors do
    resources :roles
  end

end

app/models/actor.rb
class Actor < ActiveRecord::Base
	has_many :roles
	has_many :movies, through: :roles

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :date_of_birth, presence: true

	default_scope { order(:last_name, :first_name) }

	def name
		[self.first_name, self.last_name].join(' ')
	end

	def age
		Date.today.year - self.date_of_birth.year - ((Date.today.month > self.date_of_birth.month || (Date.today.month == self.date_of_birth.month && Date.today.day >= self.date_of_birth.day)) ? 0 : 1)
	end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :roles
	has_many :actors, through: :roles

	validates :title, presence: true
	validates :year, presence: true, numericality: { only_integer: true, greater_than: 1800, less_than: Date.today.year + 2.years }
	validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10, allow_blank: true }

	default_scope { order(:title) }
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :actor
  belongs_to :movie

  validates :actor, presence: true
  validates :movie, presence: true
  validates :name, presence: true
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
	def index
		@actors = Actor.all()
	end

	def show
  	@actor = Actor.find(params[:id])
  end

  def new
  	@actor = Actor.new
  end

  def create
  	@actor = Actor.new(actor_params)

  	if @actor.save
  		redirect_to @actor
  	else
  		render 'new'
  	end
  end

  def edit
  	@actor = Actor.find(params[:id])
  end

  def update
  	@actor = Actor.find(params[:id])

  	if @actor.update(actor_params)
  		redirect_to @actor
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@actor = Actor.find(params[:id])
  	@actor.destroy

  	redirect_to actors_path
  end

  private
  	def actor_params
  		params.require(:actor).permit(:first_name, :last_name, :date_of_birth)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	def index
		@movies = Movie.all()
	end

	def show
  	@movie = Movie.find(params[:id])
  	@rating = ""

  	if @movie.rating
	  	@movie.rating.times do
	  		@rating += "★"
	  	end
	  end
  	@rating = @rating.ljust(10, '☆')
  end

  def new
  	@movie = Movie.new
  end

  def create
  	@movie = Movie.new(movie_params)

  	if @movie.save
  		redirect_to @movie
  	else
  		render 'new'
  	end
  end

  def edit
  	@movie = Movie.find(params[:id])
  end

  def update
  	@movie = Movie.find(params[:id])

  	if @movie.update(movie_params)
  		redirect_to @movie
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@movie = Movie.find(params[:id])
  	@movie.destroy

  	redirect_to movies_path
  end

  private
  	def movie_params
  		params.require(:movie).permit(:title, :year, :rating)
  	end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
	def new
		@role = Role.new
		if params[:actor_id]
			@actor = Actor.find(params[:actor_id])
			render 'new_role'
		elsif params[:movie_id]
			@movie = Movie.find(params[:movie_id])
			render 'new_cast'
		else
			raise 'Actor or Movie must be defined'
		end
	end

	def create
		if params[:actor_id]
			@actor = Actor.find(params[:actor_id])
			if @actor.roles.create(role_params)
				redirect_to @actor
			else
				render 'new'
			end
		elsif params[:movie_id]
			@movie = Movie.find(params[:movie_id])
			if @movie.roles.create(role_params)
				redirect_to @movie
			else
				render 'new'
			end
		else
			raise 'Actor and Movie must be defined'
		end
	end

	def edit
		@role = Role.find(params[:id])
	end

	def update
		@role = Role.find(params[:id])
		if @role.update(role_params)
			redirect_to @role.actor
		else
			render 'edit'
		end
	end

	def destroy
		@role = Role.find(params[:id])
		@actor = @role.actor
		@role.destroy

		redirect_to @actor
	end

	private

	def role_params
		params.require(:role).permit(:movie_id, :actor_id, :name)
	end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/actors/_form.html.haml
= form_for @actor do |f|
	- if @actor.errors.any?
		.alert.alert-danger
			%p
				%strong The following #{'error'.pluralize(@actor.errors.size)} prevented this actor from being saved:
			%ul
				- @actor.errors.full_messages.each do |msg|
					%li= msg
	.form-group
		= f.label :first_name
		= f.text_field :first_name, :class => 'form-control'
	.form-group
		= f.label :last_name
		= f.text_field :last_name, :class => 'form-control'
	.form-group
		= f.label :date_of_birth
		%br
		= f.date_select :date_of_birth, order: [:month, :day, :year], start_year: 1900, :class => 'form-control'
	= f.submit nil, :class => 'btn btn-primary'

app/views/actors/edit.html.haml
.panel-heading
	%h1.panel-title Edit Actor
.panel-body
	= render 'form'

app/views/actors/index.html.haml
.panel-heading
	%h1.panel-title Actors
.panel-body
	%table.table
		%tr
			%th Name
			%th DoB
			%th Movies
			%th
			%th
		- @actors.each do |a|
			%tr
				%td= link_to a.name, a
				%td= link_to a.date_of_birth.strftime("%m/%d/%Y"), a
				%td= a.movies.count
				%td= link_to 'Edit', edit_actor_path(a)
				%td= link_to 'Delete', actor_path(a), method: :delete, data: { confirm: "Are you sure you want to delete the actor '#{a.name}'?"}

app/views/actors/new.html.haml
.panel-heading
	%h1.panel-title New Actor
.panel-body
	= render 'form'

app/views/actors/show.html.haml
.panel-heading
	%h1.panel-title #{@actor.name} (#{@actor.age})
.panel-body
	%h2 Movie Roles
	%ul
		- @actor.roles.each do |role|
			%li #{role.name} in #{link_to role.movie.title, role.movie} (#{link_to 'Edit', edit_actor_role_path(role.actor, role)} | #{link_to 'Delete', actor_role_path(role.actor, role), method: :delete, data: { confirm: "Are you sure you want to delete the role '#{role.name}'?" }})
	%p= link_to 'Add Role', new_actor_role_path(@actor), :class => "btn btn-primary"

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title bMDB
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
		%nav.navbar.navbar-default
			.navbar-header
				%button.navbar-toggle.collapsed{ :type => 'button', :data => { :toggle => 'collapse', :target => '#bs-example-navbar-collapse-1' } }
					%span.sr-only Toggle Navigation
					%span.icon-bar
					%span.icon-bar
					%span.icon-bar
				= link_to 'bMDB', root_path, :class => 'navbar-brand'
			.collapse.navbar-collapse#bs-example-navbar-collapse-1
				%ul.nav.navbar-nav
					%li= link_to 'Movies', movies_path
					%li= link_to 'Add Movie', new_movie_path
					%li= link_to 'Actors', actors_path
					%li= link_to 'Add Actor', new_actor_path
		.container
			.row
				.col-md-10.col-md-offset-1
					.panel.panel-default
						= yield

app/views/movies/_form.html.haml
= form_for @movie do |f|
	- if @movie.errors.any?
		.alert.alert-danger
			%p
				%strong The following #{'error'.pluralize(@movie.errors.size)} prevented this movie from being saved:
			%ul
				- @movie.errors.full_messages.each do |msg|
					%li= msg
	.form-group
		= f.label :title
		= f.text_field :title, :class => 'form-control'
	.form-group
		= f.label :year
		= f.number_field :year, :class => 'form-control'
	.form-group
		= f.label :rating
		= f.number_field :rating, :class => 'form-control'
	= f.submit nil, :class => 'btn btn-primary'

app/views/movies/edit.html.haml
.panel-heading
	%h1.panel-title Edit Movie
.panel-body
	= render 'form'

app/views/movies/index.html.haml
.panel-heading
	%h1.panel-title Movies
.panel-body
	%table.table
		%tr
			%th Title
			%th Year
			%th
			%th
		- @movies.each do |m|
			%tr
				%td= link_to m.title, m
				%td= link_to m.year, m
				%td= link_to 'Edit', edit_movie_path(m)
				%td= link_to 'Delete', movie_path(m), method: :delete, data: { confirm: "Are you sure you want to delete the movie '#{m.title}'?"}

app/views/movies/new.html.haml
.panel-heading
	%h1.panel-title New Movie
.panel-body
	= render 'form'

app/views/movies/show.html.haml
.panel-heading
	%h1.panel-title #{@movie.title} (#{@movie.year})
.panel-body
	%p= @rating
	%h2 Cast
	%ul
		- @movie.roles.each do |role|
			%li #{link_to role.actor.name, role.actor} as #{role.name}
	%p= link_to 'Add Cast Member', new_movie_role_path(@movie), :class => 'btn btn-primary'

app/views/roles/_cast_form.html.haml
= form_for [@movie, @role] do |f|
	- if @role.errors.any?
		.alert.alert-danger
			%p
				%strong The following #{'error'.pluralize(@role.errors.size)} prevented this cast member from being saved:
			%ul
				- @role.errors.full_messages.each do |msg|
					%li= msg
	.form-group
		= f.label :name, 'Role Name'
		= f.text_field :name, :class => 'form-control'
	.form-group
		= f.label :actor_id
		%br
		= f.select :actor_id, Actor.all.collect { |a| [a.name, a.id] }, :class => 'form-control'
	= f.submit nil, :class => 'btn btn-primary'

app/views/roles/_role_form.html.haml
= form_for [@actor, @role] do |f|
	- if @role.errors.any?
		.alert.alert-danger
			%p
				%strong The following #{'error'.pluralize(@role.errors.size)} prevented this cast member from being saved:
			%ul
				- @role.errors.full_messages.each do |msg|
					%li= msg
	.form-group
		= f.label :name, 'Role Name'
		= f.text_field :name, :class => 'form-control'
	.form-group
		= f.label :movie_id
		%br
		= f.select :movie_id, Movie.all.collect { |m| [m.title, m.id] }, :class => 'form-control'
	= f.submit nil, :class => 'btn btn-primary'

app/views/roles/edit.html.haml
.panel-heading
	%h1.panel-title Editing #{@role.actor.name}'s Role in #{@role.movie.title}
.panel-body
	= render 'form'

app/views/roles/new_cast.html.haml
.panel-heading
	%h1.panel-title New Cast for #{@movie.title}
.panel-body
	= render 'cast_form'

app/views/roles/new_role.html.haml
.panel-heading
	%h1.panel-title New Role for #{@actor.name}
.panel-body
	= render 'role_form'